[snap_hal]
# Time between every poll
polling_interval_usec = 0
# Physical function ID
pf_id = 0
# Virtual function ID
vf_id = -1
# Emulation manager, DPU specific
emu_manager = "mlx5_0"
# Amount of Virtio requests queues, every queue is paired with a single thread for polling. 1 for single threaded mode, >1 for multithreaded mode
# Multithreaded not supported in snap_hal currently as the virtio-fs driver still only support a single Virtio queue.
nthreads = 1
# Must be a power of 2 and >= 1! The virtio-fs specification requires this
queue_depth = 64
# Filesystem tag (i.e. the name of the virtiofs device to mount for the host)
tag = "dpfs"

[rvfs_hal]
# Time between every poll
polling_interval_usec = 0

[nfs]
# The NFS server that you want to mirror
server = "10.100.0.1"
# The NFS server's path that you want to mirror
export = "/mnt/shared"

# This is for dpfs_rvfs_dpu and the dpfs_hal implementation that uses RVFS
[rvfs]
remote_uri = "10.100.0.1:31850"
dpu_uri = "10.100.0.115:31850"
# If enabled then rvfs_dpu will do RVFS and hal polling on two seperate threads
# TODO make this work for the RVFS version of hal as well?
two_threads = true

[kv]
# The remote RAMCloud server that KV will connect to
ramcloud_coordinator = "PLACEHOLDER"

[local_mirror]
dir = "/mnt/shared"
cached = false
# Enables userspace polling on the completion queue
# This causes high CPU usage!
uring_cq_polling = true
# Enables kernel polling on the submission queue
# This causes high CPU usage!
uring_sq_polling = true
